controller_list:
  - name: fake_leg_group_controller
    type: $(arg fake_execution_type)
    joints:
      - ljoint1
      - ljoint2
      - ljoint3
  - name: fake_right_group_controller
    type: $(arg fake_execution_type)
    joints:
      - rjoint1
      - rjoint2
      - rjoint3
initial:  # Define initial robot poses per group
  - group: leg_group
    pose: left_p1
  - group: right_group
    pose: right_p1